# How to fatpack with Vagrant
# vagrant >= 1.6.3 is required
#
# * fatpack build-perl
#   $ cd author
#   $ vagrant up --provision
# 
# * halt vm
#   $ vagrant halt
#
# * retry fatpack
#   $ vagrant up --provision
#     or 
#   $ vagrant reload --provision
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "../", "/perl-build"
  config.vm.provision "docker" do |d|
    d.build_image "/perl-build/author",
      args: "-t perl-build"
  end
  # docker provisoner does not block until docker run is finished, so I use shell provisioner for docker run
  config.vm.provision "shell",
    inline: "docker run -v /perl-build:/perl-build perl-build"
end

